// Combined XGBoost Models for all 9 rehabilitation gestures
// Auto-generated by train_all_models.py

import { evaluateGesture0 } from './model_gesture_0.js';
import { evaluateGesture1 } from './model_gesture_1.js';
import { evaluateGesture2 } from './model_gesture_2.js';
import { evaluateGesture3 } from './model_gesture_3.js';
import { evaluateGesture4 } from './model_gesture_4.js';
import { evaluateGesture5 } from './model_gesture_5.js';
import { evaluateGesture6 } from './model_gesture_6.js';
import { evaluateGesture7 } from './model_gesture_7.js';
import { evaluateGesture8 } from './model_gesture_8.js';

export const GESTURE_MODELS = {
    0: { name: 'ElbowFlexionLeft', evaluate: evaluateGesture0, accuracy: 0.9981 },
    1: { name: 'ElbowFlexionRight', evaluate: evaluateGesture1, accuracy: 0.9991 },
    2: { name: 'ShoulderFlexionLeft', evaluate: evaluateGesture2, accuracy: 0.9988 },
    3: { name: 'ShoulderFlexionRight', evaluate: evaluateGesture3, accuracy: 0.9997 },
    4: { name: 'ShoulderAbductionLeft', evaluate: evaluateGesture4, accuracy: 0.9973 },
    5: { name: 'ShoulderAbductionRight', evaluate: evaluateGesture5, accuracy: 0.9992 },
    6: { name: 'ShoulderForwardElevation', evaluate: evaluateGesture6, accuracy: 0.9966 },
    7: { name: 'SideTapLeft', evaluate: evaluateGesture7, accuracy: 0.9997 },
    8: { name: 'SideTapRight', evaluate: evaluateGesture8, accuracy: 0.9987 },
};

export function evaluateGesture(gestureId, features) {
    const model = GESTURE_MODELS[gestureId];
    if (!model) return null;
    const result = model.evaluate(features);
    // result is [prob_class_0, prob_class_1]
    return {
        prediction: result[1] > 0.5 ? 1 : 0,
        confidence: Math.max(result[0], result[1]),
        probCorrect: result[1],
        probIncorrect: result[0]
    };
}
